### ISSUE TITLE
update to react 18

### ISSUE THREAD

**Issue by ZahinTapadar** [jmcudd/react-jdenticon#10]
Please update the code to react 18.2.0

**Comment by jmcudd** [comment]
Thanks for the comment. I'll try to get it updated.

**Comment by ZahinTapadar** [comment]
Any update on this?

**Comment by jmcudd** [comment]
@falkon2 Can you submit a PR for the change? I don't have time to do this today.

**Comment by ZahinTapadar** [comment]
Alright will do that

**Comment by ZahinTapadar** [comment]
Does simply updating to react version 18 not Work? Or do you need to update code up for it.(im new so I wanted to know)

**Comment by jmcudd** [comment]
@falkon2 You should be good now. Update to 1.0.1 and see if that works for you. Let me know if you have any issues. Thanks.
